import { Suspense } from 'react';
import './styles/globals.css';
import Navigation from './components/Navigation.client';
import Footer from './components/Footer.client';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Suspense fallback={<div>Loading...</div>}>
          <Navigation />
        {children}
        <Footer/>
        </Suspense>
      </body>
    </html>
  );
}